files:
  MGN_ANM_DPTOS: 'https://www.dane.gov.co/files/geoportal-provisional/SHP_MGN2018_INTGRD_DEPTO.zip'
  MGN_ANM_MPIOS: 'https://www.dane.gov.co/files/geoportal-provisional/SHP_MGN2018_INTGRD_MPIO.zip'
  MGN_ANM_MPIOCL: 'https://www.dane.gov.co/files/geoportal-provisional/SHP_MGN2018_INTGRD_CLASECS.zip'
  MGN_ANM_SECTOR_RURAL: 'https://www.dane.gov.co/files/geoportal-provisional/SHP_MGN2018_INTGRD_SECTR.zip'
  MGN_ANM_SECCION_RURAL: 'https://www.dane.gov.co/files/geoportal-provisional/SHP_MGN2018_INTGRD_SECCR.zip'
  MGN_ANM_ZU: 'https://www.dane.gov.co/files/geoportal-provisional/SHP_MGN2018_INTGRD_ZCU.zip'
  MGN_ANM_SECTOR_URBANO: 'https://www.dane.gov.co/files/geoportal-provisional/SHP_MGN2018_INTGRD_SECTU.zip'
  MGN_ANM_SECCION_URBANA: 'https://www.dane.gov.co/files/geoportal-provisional/SHP_MGN2018_INTGRD_SECCU.zip'
  MGN_ANM_MANZANA: 'https://www.dane.gov.co/files/geoportal-provisional/SHP_MGN2018_INTGRD_MANZ.zip'
load:
  MGN_ANM_DPTOS: 'e4a0ec7c-403b-4f3a-863e-590de8256a47'
  MGN_ANM_MPIOS: '429d195a-a216-45fe-9662-f7284a829483'
  MGN_ANM_MPIOCL: '6d488b10-0c11-4037-b2a5-281418d44fff'
  MGN_ANM_SECTOR_RURAL: '258535e3-d34f-4078-bc78-0ead51151e2f'
  MGN_ANM_SECCION_RURAL: '77d0bc75-6252-4e10-bb95-76ea4bb870df'
  MGN_ANM_ZU: 'e5086aa2-a28d-40de-b919-d221e614d8cb'
  MGN_ANM_SECTOR_URBANO: 'b7aeb393-d4b9-4604-96d5-956c13f9b30e'
  MGN_ANM_SECCION_URBANA: '0f145cef-d1d2-4b72-875d-76bc73e33b92'
  MGN_ANM_MANZANA: 'c8dddb82-91f3-4571-b0fd-f0135c0db950'
